### ISSUE TITLE
Readme + Authors

### ISSUE THREAD

**Issue by lduarte1991** [lduarte1991/hxat#40]
@arthurian Once governance is figured out we should rewrite readme and add an authors page. I'll leave the readme as is for now, yours was used during the merge for some reason I didn't realize haha.

**Comment by arthurian** [comment]
@lduarte1991 Completely agree. I'm not sure why we used the ATG version either lol. The README definitely needs an overhaul since some of the info on there (end-user documentation) is already covered elsewhere, and developer documentation, is probably best stored somewhere else (either a separate document or the wiki?). I like the idea of adding an authors page too.
