### ISSUE TITLE
Project Name Change?

### ISSUE THREAD

**Issue by lduarte1991** [lduarte1991/hxat#50]
@arthurian I doubt this would be an issue on your end but wanted to double check to make sure. We would like to rename the github project to be "HxAT". Let me know if there's a reason why I shouldn't. Thanks!

**Comment by arthurian** [comment]
It shouldn't impact us in any way, since we're pulling/pushing from our fork of the project. Hopefully github will keep track of the fork when the name changes.

Just curious, but what's the motivation for changing the name to HxAT?  The new project name seems much less descriptive to the existing name.

**Comment by lduarte1991** [comment]
Stands for the HarvardX Annotation Tool. It'll be referred to as such in documentation and everything but the acronym is just to make my life easier lol. hx-annotations-lti was just a vague default I picked out and we seemed to have settled on calling it the HxAT.

**Comment by lduarte1991** [comment]
And according to Rashmi working on the Mirador project, Github is smart enough to redirect old urls to the new one.

**Comment by arthurian** [comment]
I figured github would be smart enough to track that, but you never know. 

That makes sense, acronyms always make life easier. I think we're going to stick with calling our project annotationsx. You're welcome to use that name if you want, but I'd have to agree that HxAT makes for much less typing! :smile:
